VIDYUT_DIR ?= ../../../
AMREX_HOME ?= ../../../../amrex

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ${VIDYUT_DIR}/test/Make.vidyut
