#ifndef Vidyut_univconstants_H_
#define Vidyut_univconstants_H_

#define N_A 6.02214076e23
#define K_B 1.380649e-23
#define PI 3.14159265358979323846264338327950288
#define P_NTP 101325.0 //pressure at normal pressure and temperature
#define T_NTP 293.15  //temperature at normal pressure and temperature
#define FARADCONST 96485.332
#define GASCONST   8.31446261815324
#define ECHARGE    1.60217662e-19
#define EPS0       8.854187817e-12
#define eV ECHARGE/K_B
#define FBYR FARADCONST/GASCONST
#define ME 9.10938188e-31 //electron mass
#define M_AMU 1.66054e-27 //atomic mass units
#define TDUNIT 1e-21 //townsend in V m2
#define fivebythree 5.0/3.0
#define twothird 2.0/3.0
#endif
