#ifndef Vidyut_H_
#define Vidyut_H_

#include <AMReX_MLMG.H>

#include <string>
#include <limits>
#include <memory>

#ifdef _OPENMP
#include <omp.h>
#endif

#ifdef AMREX_USE_HYPRE
#include <AMReX_Hypre.H>
#endif

#include <AMReX_AmrCore.H>
#include <AMReX_BCRec.H>
#include <ProbParm.H>

#include <AMReX_MLABecLaplacian.H>
#include <UnivConstants.H>
#include <VarDefines.H>


using namespace amrex;

class Vidyut : public amrex::AmrCore
{
public:
    ////////////////
    // public member functions

    // constructor - reads in parameters from inputs file
    //             - sizes multilevel arrays and data structures
    Vidyut();
    virtual ~Vidyut();

    // advance solution to final time
    void Evolve();

    // initializes multilevel data
    void InitData();

    // Make a new level using provided BoxArray and DistributionMapping and
    // fill with interpolated coarse level data.
    // overrides the pure virtual function in AmrCore
    virtual void MakeNewLevelFromCoarse(int lev, amrex::Real time, 
                                        const amrex::BoxArray& ba, 
                                        const amrex::DistributionMapping& dm) override;

    // Remake an existing level using provided BoxArray and DistributionMapping and
    // fill with existing fine and coarse data.
    // overrides the pure virtual function in AmrCore
    virtual void RemakeLevel(int lev, amrex::Real time, 
                             const amrex::BoxArray& ba, 
                             const amrex::DistributionMapping& dm) override;

    // Delete level data
    // overrides the pure virtual function in AmrCore
    virtual void ClearLevel(int lev) override;

    // Make a new level from scratch using provided BoxArray and DistributionMapping.
    // Only used during initialization.
    // overrides the pure virtual function in AmrCore
    virtual void MakeNewLevelFromScratch(int lev, amrex::Real time, 
                                         const amrex::BoxArray& ba, 
                                         const amrex::DistributionMapping& dm) override;

    // tag all cells for refinement
    // overrides the pure virtual function in AmrCore
    virtual void ErrorEst(int lev, amrex::TagBoxArray& tags, 
                          amrex::Real time, int ngrow) override;

   void compute_scalar_transport_flux(int lev, const int num_grow, MultiFab& Sborder, 
                                             Array<MultiFab,AMREX_SPACEDIM>& flux, 
                                             Array<MultiFab,AMREX_SPACEDIM>& efield, 
                                             Real time,int specid);

    void compute_dsdt(int lev, const int num_grow, int specid, 
                      MultiFab& Sborder, 
        Array<MultiFab,AMREX_SPACEDIM>& flux, 
        MultiFab& rxn_src,
        MultiFab& dsdt,
        Real time, Real dt);

    void solve_potential(Real current_time, Vector<MultiFab>& Sborder, 
                         Vector<int>& bc_lo, Vector<int>& bc_hi, 
                         Vector<Array<MultiFab,AMREX_SPACEDIM>>& efield_fc);

    void update_explsrc_at_all_levels(int specid, Vector<MultiFab>& Sborder,
                                            Vector<Array<MultiFab,AMREX_SPACEDIM>>& flux,
                                            Vector<MultiFab>& rxn_src, 
                                            Vector<Array<MultiFab,AMREX_SPACEDIM>>& efield,
                                            Vector<MultiFab>& expl_src, 
                                            amrex::Real cur_time);
    
    void update_rxnsrc_at_all_levels(Vector<MultiFab>& Sborder,
                                            Vector<MultiFab>& rxn_src, 
                                            amrex::Real cur_time);
    
    void implicit_solve_scalar(Real current_time,Real dt,int spec_id,
            Vector<MultiFab>& Sborder, Vector<MultiFab>& dsdt_expl,
                         Vector<int>& bc_lo, Vector<int>& bc_hi,
                         Vector<Array<MultiFab,AMREX_SPACEDIM>>& grad_fc);

    void compute_elecenergy_source(int lev, const int num_grow, 
                            MultiFab& Sborder, 
                            MultiFab& rxnsrc, 
                            Array<MultiFab,AMREX_SPACEDIM>& efield, 
                            Array<MultiFab,AMREX_SPACEDIM>& gradne, 
                            MultiFab& dsdt,
                            Real time, Real dt);

    // compute dt from CFL considerations
    void find_time_scales(int lev,amrex::Real& dt_edrift,amrex::Real &dt_ediff,
            amrex::Real& dt_diel_relax);

    static ProbParm* h_prob_parm;
    static ProbParm* d_prob_parm;
   
    std::unique_ptr<amrex::MLABecLaplacian> linsolve_ptr;
    
    ////////////////
    amrex::Gpu::ManagedVector<Real> refine_phi;
    amrex::Gpu::ManagedVector<Real> refine_phigrad;
    amrex::Gpu::ManagedVector<int> refine_phi_comps;

    amrex::Vector<int> istep;     // which step?
    amrex::Vector<int> nsubsteps; // how many substeps on each level?

    // keep track of old time, new time, and time step at each level
    amrex::Vector<amrex::Real> t_new;
    amrex::Vector<amrex::Real> t_old;
    amrex::Vector<amrex::Real> dt;

    // array of multifabs to store the solution at each level of refinement
    // after advancing a level we use "swap".
    amrex::Vector<amrex::MultiFab> phi_new;
    amrex::Vector<amrex::MultiFab> phi_old;

    // this is essentially a 2*DIM integer array storing the physical boundary
    // condition types at the lo/hi walls in each direction
    amrex::Vector<BCRec> bcspec; // 1-component

    // maximum number of steps and stop time
    int max_step = std::numeric_limits<int>::max();
    amrex::Real stop_time = std::numeric_limits<amrex::Real>::max();


    // if >= 0 we restart from a checkpoint
    std::string restart_chkfile = "";


    amrex::Vector<int> pot_bc_lo{ROBINBC, ROBINBC, ROBINBC};
    amrex::Vector<int> pot_bc_hi{ROBINBC, ROBINBC, ROBINBC};
    
    amrex::Vector<int> eden_bc_lo{ROBINBC, ROBINBC, ROBINBC};
    amrex::Vector<int> eden_bc_hi{ROBINBC, ROBINBC, ROBINBC};
    
    amrex::Vector<int> eenrg_bc_lo{ROBINBC, ROBINBC, ROBINBC};
    amrex::Vector<int> eenrg_bc_hi{ROBINBC, ROBINBC, ROBINBC};
    
    amrex::Vector<int> ion_bc_lo{ROBINBC, ROBINBC, ROBINBC};
    amrex::Vector<int> ion_bc_hi{ROBINBC, ROBINBC, ROBINBC};
    
    amrex::Vector<int> neutral_bc_lo{ROBINBC, ROBINBC, ROBINBC};
    amrex::Vector<int> neutral_bc_hi{ROBINBC, ROBINBC, ROBINBC};
    
    // advective cfl number - dt = cfl*dx/umax
    amrex::Real cfl = 0.7;

    amrex::Real fixed_dt=1e-12;

    amrex::Real linsolve_reltol = 1e-10;
    amrex::Real linsolve_abstol = 1e-10;
    amrex::Real linsolve_bot_reltol = 1e-10;
    amrex::Real linsolve_bot_abstol = -1.0;
    amrex::Real min_species_density=1e-20;
    amrex::Real min_electron_temp=0.1*eV;

    amrex::Real gas_pressure=101325.0;
    amrex::Real gas_temperature=300.0;

    amrex::Vector<std::string> plasma_param_names;
    amrex::Vector<std::string> allvarnames;

    int linsolve_num_pre_smooth = 2;
    int linsolve_num_post_smooth = 2;
    int linsolve_num_final_smooth = 8;
    int linsolve_num_bottom_smooth = 0;

    int linsolve_maxiter=100;
    int linsolve_max_coarsening_level=10;
    int bound_specden=0;

    // Include physics
    int elecenergy_solve=0;
    int do_reactions=1;
    int do_transport=1;
    int do_spacechrg=1;

    // how often each level regrids the higher levels of refinement
    // (after a level advances that many time steps)
    int regrid_int = 2;

    // hyperbolic refluxing as part of multilevel synchronization
    int do_reflux = 1;

    int use_hypre=0;

    // plotfile prefix and frequency
    std::string plot_file{"plt"};
    int plot_int = -1;

    // checkpoint prefix and frequency
    std::string chk_file{"chk"};
    int chk_int = -1;

    // Electron species index
    int E_IDX = 0;

private:
    ////////////////
    // private member functions

    // read in some parameters from inputs file
    void ReadParameters();

    // set covered coarse cells to be the average of overlying fine cells
    void AverageDown();

    // more flexible version of AverageDown() that lets you average down across multiple levels
    void AverageDownTo(int crse_lev);

    // compute a new multifab by coping in phi from valid region and filling ghost cells
    // works for single level and 2-level cases (fill fine grid ghost by interpolating from coarse)
    void FillPatch(int lev, amrex::Real time, amrex::MultiFab& mf, int icomp, int ncomp);

    // fill an entire multifab by interpolating from the coarser level
    // this comes into play when a new level of refinement appears
    void FillCoarsePatch(int lev, amrex::Real time, amrex::MultiFab& mf, int icomp, int ncomp);

    // utility to copy in data from phi_old and/or phi_new into another multifab
    void GetData(int lev, amrex::Real time, 
                 amrex::Vector<amrex::MultiFab*>& data, amrex::Vector<amrex::Real>& datatime);

    // a wrapper for EstTimeStep(0
    void ComputeDt();

    // put together an array of multifabs for writing
    amrex::Vector<const amrex::MultiFab*> PlotFileMF() const;

    // write plotfile to disk
    void WritePlotFile(int plotfilenum) const;

    // write checkpoint file to disk
    void WriteCheckpointFile(int chkfilenum) const;

    // read checkpoint file from disk
    void ReadCheckpointFile();

    // utility to skip to next line in Header
    static void GotoNextLine(std::istream& is);

    Vector<int> bg_specid_list{-1};

};

#endif
